export const emojiMapping = {
    '[微笑]': ':slightly_smiling_face:', ':slightly_smiling_face:': '[微笑]',
    '[高兴]': ':blush:', ':blush:': '[高兴]',
    '[委屈]': ':white_frowning_face:', ':white_frowning_face:': '[委屈]',
    '[喜欢]': ':heart_eyes:', ':heart_eyes:': '[喜欢]',
    '[飞吻]': ':kissing_heart:', ':kissing_heart:': '[飞吻]',
    '[酷]': ':sunglasses:', ':sunglasses:': '[酷]',
    '[假笑]': ':smirk:', ':smirk:': '[假笑]',
    '[俏皮]': ':stuck_out_tongue_winking_eye:', ':stuck_out_tongue_winking_eye:': '[俏皮]',
    '[困]': ':sleepy:', ':sleepy:': '[困]',
    '[笑呵呵]': ':grinning:', ':grinning:': '[笑呵呵]',
    '[笑哭]': ':joy:', ':joy:': '[笑哭]',
    '[累]': ':tired_face:', ':tired_face:': '[累]',
    '[苦笑]': ':sweat_smile:', ':sweat_smile:': '[苦笑]',
    '[开心]': ':grin:', ':grin:': '[开心]',
    '[伤心]': ':sob:', ':sob:': '[伤心]',
    '[无言]': ':open_mouth:', ':open_mouth:': '[无言]',
    '[大笑]': ':laughing:', ':laughing:': '[大笑]',
    '[天真]': ':innocent:', ':innocent:': '[天真]',
    '[恶魔]': ':smiling_imp:', ':smiling_imp:': '[恶魔]',
    '[担心]': ':worried:', ':worried:': '[担心]',
    '[疲倦]': ':sleeping:', ':sleeping:': '[疲倦]',
    '[沮丧]': ':pensive:', ':pensive:': '[沮丧]',
    '[迷茫]': ':confused:', ':confused:': '[迷茫]',
    '[困惑]': ':confounded:', ':confounded:': '[困惑]',
    '[生气]': ':rage:', ':rage:': '[生气]',
    '[努力]': ':triumph:', ':triumph:': '[努力]',
    '[汗]': ':sweat:', ':sweat:': '[汗]',
    '[恐惧]': ':fearful:', ':fearful:': '[恐惧]',
    '[尖叫]': ':scream:', ':scream:': '[尖叫]',
    '[倒立]': ':upside_down_face:', ':upside_down_face:': '[倒立]',
    '[脸红]': ':flushed:', ':flushed:': '[脸红]',
    '[财迷]': ':money_mouth_face:', ':money_mouth_face:': '[财迷]',
    '[惊讶]': ':astonished:', ':astonished:': '[惊讶]',
    '[生病]': ':mask:', ':mask:': '[生病]',
    '[白眼]': ':face_with_rolling_eyes:', ':face_with_rolling_eyes:': '[白眼]',
    '[中立]': ':neutral_face:', ':neutral_face:': '[中立]',
    '[拥抱]': ':hugging_face:', ':hugging_face:': '[拥抱]',
    '[受伤]': ':face_with_head_bandage:', ':face_with_head_bandage:': '[受伤]',
    '[闭嘴]': ':zipper_mouth_face:', ':zipper_mouth_face:': '[闭嘴]',
    '[感冒]': ':sneezing_face:', ':sneezing_face:': '[感冒]',
    '[书呆子]': ':nerd_face:', ':nerd_face:': '[书呆子]',
    '[发烧]': ':face_with_thermometer:', ':face_with_thermometer:': '[发烧]',
    '[思考]': ':thinking_face:', ':thinking_face:': '[思考]',
    '[黑脸]': ':new_moon_with_face:', ':new_moon_with_face:': '[黑脸]',
    '[头骨]': ':skull:', ':skull:': '[头骨]',
    '[心]': ':heart:', ':heart:': '[心]',
    '[心碎]': ':broken_heart:', ':broken_heart:': '[心碎]',
    '[反手]': ':raised_back_of_hand:', ':raised_back_of_hand:': '[反手]',
    '[耶]': ':v:', ':v:': '[耶]',
    '[握紧拳头]': ':fist:', ':fist:': '[握紧拳头]',
    '[赞]': ':+1:', ':+1:': '[赞]',
    '[踩]': ':-1:', ':-1:': '[踩]',
    '[手指向上]': ':point_up_2:', ':point_up_2:': '[手指向上]',
    '[手指向下]': ':point_down:', ':point_down:': '[手指向下]',
    '[手指向左]': ':point_left:', ':point_left:': '[手指向左]',
    '[手指向右]': ':point_right:', ':point_right:': '[手指向右]',
    '[握手]': ':handshake:', ':handshake:': '[握手]',
    '[拳头]': ':punch:', ':punch:': '[拳头]',
    '[挥手]': ':wave:', ':wave:': '[挥手]',
    '[鼓掌]': ':clap:', ':clap:': '[鼓掌]',
    '[肌肉]': ':muscle:', ':muscle:': '[肌肉]',
    '[金属礼]': ':the_horns:', ':the_horns:': '[金属礼]',
    '[OK]': ':ok_hand:', ':ok_hand:': '[OK]',
    '[开放]': ':open_hands:', ':open_hands:': '[开放]',
    '[打电话]': ':call_me_hand:', ':call_me_hand:': '[打电话]',
    '[祈福]': ':pray:', ':pray:': '[祈福]',
    '[炸弹]': ':bomb:', ':bomb:': '[炸弹]',
    '[便便]': ':poop:', ':poop:': '[便便]',
    '[鬼魂]': ':ghost:', ':ghost:': '[鬼魂]',
    '[月亮]': ':crescent_moon:', ':crescent_moon:': '[月亮]',
    '[太阳]': ':sunny:', ':sunny:': '[太阳]',
    '[闪电]': ':zap:', ':zap:': '[闪电]',
    '[不能说]': ':speak_no_evil:', ':speak_no_evil:': '[不能说]',
    '[不敢看]': ':see_no_evil:', ':see_no_evil:': '[不敢看]',
    '[不要听]': ':hear_no_evil:', ':hear_no_evil:': '[不要听]',
    '[玫瑰]': ':rose:', ':rose:': '[玫瑰]',
    '[气球]': ':balloon:', ':balloon:': '[气球]',
    '[礼物]': ':gift:', ':gift:': '[礼物]',
    '[派对]': ':tada:', ':tada:': '[派对]',
    '[心型礼盒]': ':gift_heart:', ':gift_heart:': '[心型礼盒]',
    '[红唇]': ':kiss:', ':kiss:': '[红唇]',
    '[篮球]': ':basketball:', ':basketball:': '[篮球]',
    '[足球]': ':soccer:', ':soccer:': '[足球]',
    '[钱袋]': ':moneybag:', ':moneybag:': '[钱袋]',
    '[男士]': ':mens:', ':mens:': '[男士]',
    '[女士]': ':womens:', ':womens:': '[女士]',
    '[终点]': ':checkered_flag:', ':checkered_flag:': '[终点]',
    '[多云]': ':partly_sunny:', ':partly_sunny:': '[多云]',
    '[雷雨]': ':thunder_cloud_and_rain:', ':thunder_cloud_and_rain:': '[雷雨]',
    '[雪花]': ':snowflake:', ':snowflake:': '[雪花]',
    '[错误]': ':heavy_multiplication_x:', ':heavy_multiplication_x:': '[错误]',
    '[正确]': ':heavy_check_mark:', ':heavy_check_mark:': '[正确]',
    '[叹号]': ':exclamation:', ':exclamation:': '[叹号]',
    '[警告标志]': ':warning:', ':warning:': '[警告标志]',
    '[版权符号]': ':copyright:', ':copyright:': '[版权符号]',
    '[注册商标符号]': ':registered:', ':registered:': '[注册商标符号]',
}

const emojiData = {
    '表情': [
        '[微笑]', '[高兴]', '[委屈]', '[喜欢]', '[飞吻]', '[酷]',
        '[假笑]', '[俏皮]', '[困]', '[笑呵呵]', '[笑哭]', '[累]',
        '[苦笑]', '[开心]', '[伤心]', '[无言]', '[大笑]', '[天真]',
        '[恶魔]', '[担心]', '[疲倦]', '[沮丧]', '[迷茫]', '[困惑]',
        '[生气]', '[努力]', '[汗]', '[恐惧]', '[尖叫]', '[倒立]',
        '[脸红]', '[财迷]', '[惊讶]', '[生病]', '[白眼]', '[中立]',
        '[拥抱]', '[受伤]', '[闭嘴]', '[感冒]', '[书呆子]', '[发烧]',
        '[思考]', '[黑脸]', '[头骨]', '[心]', '[心碎]', '[反手]',
        '[耶]', '[握紧拳头]', '[赞]', '[踩]', '[手指向上]', '[手指向下]',
        '[手指向左]', '[手指向右]', '[握手]', '[拳头]', '[挥手]', '[鼓掌]',
        '[肌肉]', '[金属礼]', '[OK]', '[开放]', '[打电话]', '[祈福]',
        '[炸弹]', '[便便]', '[鬼魂]', '[月亮]', '[太阳]', '[闪电]',
        '[不能说]', '[不敢看]', '[不要听]', '[玫瑰]', '[气球]', '[礼物]',
        '[派对]', '[心型礼盒]', '[红唇]', '[篮球]', '[足球]', '[钱袋]',
        '[男士]', '[女士]', '[终点]', '[多云]', '[雷雨]', '[雪花]',
        '[错误]', '[正确]', '[叹号]', '[警告标志]', '[版权符号]', '[注册商标符号]',
    ]
}

export default emojiData
