// pc or phone
export const SET_MODE = 'SET_MODE'

export const RESET_DROPDOWN = 'RESET_DROPDOWN'

export const SET_REDPOINT = 'SET_REDPOINT'

export const SET_POWER_LIST = 'SET_POWER_LIST'

export const GET_PZ_DATA = 'GET_PZ_DATA'

export const SET_HOTEL_LIST = 'SET_HOTEL_LIST'

export const All_PRODUCTS = 'All_PRODUCTS'

export const PZ_PRODUCTS = 'PZ_PRODUCTS'

export const DEL_PZ = 'DEL_PZ'

export const ALL_CK_LOCATIONS = 'ALL_CK_LOCATIONS'

export const SELECT_ONE_INFO = 'SELECT_ONE_INFO'

export const GET_DETAIL = 'GET_DETAIL'

export const GET_ONE_USER_INFO = 'GET_ONE_USER_INFO'

export const GET_ROLE_RES = 'GET_ROLE_RES'

export const BAR_CODE = 'BAR_CODE'

export const GET_LOCAT_PRODUCT = 'GET_LOCAT_PRODUCT'

export const GET_CK_LOCATION = 'GET_CK_LOCATION'

export const GET_PRODUCT_BATCH = 'GET_PRODUCT_BATCH'

export const DEL_LOCATION = 'DEL_LOCATION'

export const SAVE_PARAMS = 'SAVE_PARAMS'

export const SAVE_WP_DATA = 'SAVE_WP_DATA'

export const COPY_TRELLO = 'COPY_TRELLO';

export const SAVE_ITEM = 'SAVE_ITEM'

export const VIP_CARD_ADD_GRADE = 'VIP_CARD_ADD_GRADE'

export const INSERT_TEXT = 'INSERT_TEXT'
export const INSERT_TEXT_END = 'INSERT_TEXT_END'

export const SET_PLAYING_VOICE_ELEMENT = 'SET_PLAYING_VOICE_ELEMENT'

export const SET_WX_LOCATION_STATUS = 'SET_WX_LOCATION_STATUS'
export const SET_WX_LOCATION = 'SET_WX_LOCATION'
export const SET_WX_UPLOAD_VOICE_STATUS = 'SET_WX_UPLOAD_VOICE_STATUS'
export const SET_WX_UPLOAD_VOICE = 'SET_WX_UPLOAD_VOICE'
export const SET_WX_UPLOAD_IMAGE_STATUS = 'SET_WX_UPLOAD_IMAGE_STATUS'
export const SET_WX_UPLOAD_IMAGE = 'SET_WX_UPLOAD_IMAGE'

export const SET_BOTTOM_TOAST = 'SET_BOTTOM_TOAST'

// user
export const SET_TOKEN = 'SET_TOKEN'

export const SET_ROLES = 'SET_ROLeS'

export const SET_USERINFO = 'SET_USERINFO'

export const SET_SERVICE_NUMBER_LIST = 'SET_SERVICE_NUMBER_LIST'
export const SET_CURRENT_CARDURL = 'SET_CURRENT_CARDURL'

export const UP_TOKEN_SEED = 'UP_TOKEN_SEED'
//fixedAsset

export const GET_ASSETS_CLASS = 'GET_ASSETS_CLASS'
export const GET_CHANGE_WAY = 'GET_CHANGE_WAY'
export const GET_STORE_PLACE = 'GET_STORE_PLACE'
export const GET_USE_STATE = 'GET_USE_STATE'
export const GET_VOUCHER_CODE = 'GET_VOUCHER_CODE'
export const GET_DEPRECIATION_METHOD = 'GET_DEPRECIATION_METHOD'
